name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    # Prevent recursive commits
    if: "!contains(github.event.head_commit.message, 'docs: update changelog date')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Unreleased section to CHANGELOG
        run: |
          if ! grep -q '^## \[Unreleased\]' CHANGELOG.md; then
            DATE=$(date +'%Y-%m-%d')
            # Insert after introductory lines
            sed -i "3a## [Unreleased] - $DATE\n" CHANGELOG.md
          else
            echo "Unreleased section already exists"
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog date [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}